version: '3.1'

services:

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_USER: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 5432:5432

  web:
    build:
      context: ./docker/stage
      dockerfile: Dockerfile
    ports:
    - 8080:8000
    depends_on:
      - db
      - adminer
